# Generated by Django 2.0 on 2019-09-16 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(0, 'Рубли'), (1, 'Доллары'), (2, 'Евро')], verbose_name='Код валюты')),
                ('value', models.BigIntegerField(verbose_name='Количество валюты в минимальных единицах')),
            ],
        ),
        migrations.CreateModel(
            name='HystoryOperationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(choices=[(0, 'Снятие наличных'), (1, 'Пополнение счета'), (2, 'Проверка баланса')], verbose_name='Код операации')),
                ('currency', models.IntegerField(choices=[(0, 'Рубли'), (1, 'Доллары'), (2, 'Евро')], verbose_name='Код валюты')),
                ('value', models.BigIntegerField(verbose_name='Количество валюты в минимальных единицах')),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_access_data', models.DateTimeField(auto_now=True)),
                ('balance', models.ManyToManyField(to='api.CurrencyModel')),
                ('hystory', models.ManyToManyField(to='api.HystoryOperationsModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
